version: 2.1
orbs:
  node: circleci/node@5.0.1
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Running tests...”
          npm run test
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Building project...”
          npm run build
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test